import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DashboardProvider } from "@/app/_lib/providers/DashboardProvider";
import Navigation from "@/app/_lib/components/Navigation";
import Footer from "@/app/_lib/components/Footer";

// Font family
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Font family
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Meta description
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        <DashboardProvider>{children}</DashboardProvider>
        <Footer />
      </body>
    </html>
  );
}
